require: rubocop-rails

Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'lib/tasks/fly.rake'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/urls_controller.rb'
Metrics/MethodLength:
  Max: 20
Rails:
  Enabled: true
